# Site settings
title: Full Stack Software Engineer
name: Andrew Shults 

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/Drewshults
 - title: StackOverflow
   url: https://stackoverflow.com/users/11424802/andrew-shults
 - title: LinkedIn
   url: https://www.linkedin.com/in/andrew-shults/


#Any buzzword skills you want to include
skills:
 - SQL
 - C#
 - ASP.net MVC 
 - Html/CSS
 - Product management
 - API design
 - Javascript
 - Java
 - VB.Net

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles: 
   title: Software Specialist
   start: 2019
   end: 2020
   employer: Watthour Engineering 
   description: 
   -Software based IT support for multiple applications used to test electronic meter hardware for accuracy.
   -Daily SCRUM regarding new software releases.
   -Save, back up, edit and copy customer databases in Microsoft SQL Management Studio.
   -Convert older Sybase databases into new SQL Databases.
   -Write and execute queries for customer databases in Microsoft SQL Management Studio.
   -Troubleshoot customer issues with databases/software by evaluating SQL tables, looking at code
   based errors, and going through debug files.
   -Test code to fix software issues.
   -Work in Azure DevOps TFS within Visual Studio.
   -Creating, importing, and exporting data views for customer use within meter testing software.
(Customer tells me what they want their data view to look like then I design it.).
   -Document customer software issues, keep track of them and communicate with team using Jira and Salesforce.
   -Resolve customer software and database issues.
   -Data verification and checks for inconsistencies.
   -Create new server instances and create remote server instances while assigning permission levels.
   -Assist customer with installing and setting up their Databases.
   -Evaluate customer needs regarding functionality and create software enhancement requests.
   -Involvement in the entire software development process from start, finish, to support.
   -Excellence in Customer Service.
   -Assign, create, and document software license keys.
   -Experience working remotely throughout the Coronavirus pandemic.


#Education is required
education:
 - level: Associate of Science
   date: 2019
   subject: Software Engineering Technology
   school: Holmes CC

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   courses:
    - title: Functional Programming Principles in Scala
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: September 16, 2013
    - title: Algorithms Design and Analysis, Part 1
      link: https://www.coursera.org/specializations/algorithms
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
speakerdeck:
   profileurl: https://speakerdeck.com/robhinds
   talks:
    - title: Product Management for Engineers
      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
      conference: API Conference, Berlin 2018
    - title: Agile Machine Learning - from Theory to Production
      speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
      conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
github:


#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/11424802/andrew-shults
   flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
  I am an engineer with 4.5 years experience working in technology. I have primarily worked in SQL, but have worked across a broad range of technologies thereon: C#, Javascript, ASP.Net MVC, Azure DevOps, Salesforce, VB.Net. As well as spending a reasonable amount of time building applications for the web, which has given me an exposure to a range of javascript technologies over the years, through jQuery, extjs, knockout, backbone and most recently to React. <br/><br/>
  I enjoy building interesting products, with a good Product Management focus and a good emphasis on good engineering principles and clean code.<br/><br/>

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Scala</strong>: My current role uses Scala as the primary language and have been building applications in Scala for the last two years. I am familiar with a range of Scala libraries, such as <a target="_blank" href="https://automateddeveloper.blogspot.com/2017/12/an-opinionated-guide-to-building-apis.html"> Akka-Http for building microservices</a> and <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/09/generic-programming-with-scala.html"> Shapeless for generic programming</a>, as well as familiar with a range of <a target="_blank" href="https://basementcrowd.com/2018/11/28/scala-the-aux-pattern-path-dependent-types/" >functional programming techniques available</a>.<br/><br/>
   <strong>Java</strong>: I am experienced in a variety of Java API’s and frameworks. I have worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others. <br/><br/>
   <strong>Groovy</strong> I have used Groovy as a language in production for ~4 years and I am familiar with many of the languages features (such as writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>) and quirks (such as <a target="_blank" href="https://dzone.com/articles/groovy-retrospective-an-addendum-memory-usage-perm">memory leak issues</a>). <br/><br/>
   <strong>Cloud platforms</strong>: I have primarily used AWS for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of AWS offerings, including EC2, RDS, S3, Cogito, <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/05/serverless-with-aws-lambda-scala.html">Lambda</a> and its more recent <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/10/machine-learning-with-aws-scala.html">Machine Learning capabilities</a>.<br/><br/>
   <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap, LESS, SASS, Backbone/Underscore/Require. More recently I have written React applications (primarily using the Create React App framework, and extending them)<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/AWS. <br/><br/>
   As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="https://projects.spring.io/spring-social/">https://projects.spring.io/spring-social/</a>. <br/><br/>
   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="https://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
