# Site settings
title: Full Stack Software Engineer
name: Andrew Shults 

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/Drewshults
 - title: StackOverflow
   url: https://stackoverflow.com/users/11424802/andrew-shults
 - title: LinkedIn
   url: https://www.linkedin.com/in/andrew-shults/


#Any buzzword skills you want to include
skills:
 - SQL
 - C Sharp
 - ASP.net MVC 
 - Html/CSS
 - Product management
 - API design
 - Javascript
 - Java
 - VB.Net

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Software Specialist
   start: 2020
   end: 2021
   employer: Watthour Engineering
   description: Engineering company that creates the Software and Hardware to test electronic meters for accuracy. My job consisted of management over Wattnet Basic Express software suites for customer electronic meter accuracy testing Software in production. Software based IT support for multiple applications used to test electronic meter hardware for
   accuracy. Experience with Legacy software systems, getting those upgraded, configuring drivers and fixing broken things. Daily SCRUM for Software. Save, back up, edit and copy customer databases in Microsoft SQL Management Studio. Convert older Sybase databases into new SQL Databases. Write and execute queries for customer databases in Microsoft SQL Management Studio. Troubleshoot customer issues with databases/software by evaluating SQL tables, looking at code
   based errors, and going through debug files. Test code to fix software issues. Work in Azure DevOps TFS. Visual Studio 2017-2019. SQL Server Management Studio 2008-2020. Creating, importing, and exporting data views for customer use within meter testing software. Document customer software issues, keep track of them and communicate with team using Jira, Salesforce, and MS teams. Resolve customer software and database issues. Data verification and checks for inconsistencies. Create new server instances and create remote server instances while assigning permission levels. Assist customer with installing and setting up their Databases. Evaluate customer needs regarding functionality and create software enhancement requests. Involvement in the entire software development process from start, finish, to support. Excellence in Customer Service. Assign, create, and document software license keys. Edit code in order to manipulate data. Experience working remotely throughout the Coronavirus pandemic. 

- title: 
   start: 2016
   end: 2017
   employer: Emerald Street Ventures
   description: Emerald Street Ventures was established as an incubator vehicle for the development of a number of software and legal-tech projects, and a rapidly growing, London-based start-up using innovative technologies to revolutionise and change the software and legal-tech landscape. Working with a range of cutting edge technologies and techniques including Scala, Cassandra, CoreOS, a variety of Machine Learning techniques.
 - title: Senior Engineer
   start: 2012
   end: 2016
   employer: 
   description: Covestor is an investment marketplace startup that was successfully acquired by Interactive Brokers in 2015. <br/> Working as a senior engineer, I worked closely with the CTO and across the full-stack, I was involved in all aspects of the technology including the website and back-end services.
 - title: Associate Manager
   start: 2005
   end: 2012
   employer:
   description: Working on a range of functional and technical roles, primarily working on client sites in Financial Services in London and Europe.


#Education is required
education:
 - level: Associate of Science
   date: 2019
   subject: Software Engineering Technology
   school: Holmes CC

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   courses:
    - title: Functional Programming Principles in Scala
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: September 16, 2013
    - title: Algorithms Design and Analysis, Part 1
      link: https://www.coursera.org/specializations/algorithms
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
speakerdeck:
   profileurl: https://speakerdeck.com/robhinds
   talks:
    - title: Product Management for Engineers
      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
      conference: API Conference, Berlin 2018
    - title: Agile Machine Learning - from Theory to Production
      speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
      conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
github:


#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/11424802/andrew-shults
   flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
  I am an engineer with 4.5 years experience working in technology. I have primarily worked in SQL, but have worked across a broad range of technologies thereon: C#, Javascript, ASP.Net MVC, Azure DevOps, Salesforce, VB.Net. As well as spending a reasonable amount of time building applications for the web, which has given me an exposure to a range of javascript technologies over the years, through jQuery, extjs, knockout, backbone and most recently to React. <br/><br/>
  I enjoy building interesting products, with a good Product Management focus and a good emphasis on good engineering principles and clean code.<br/><br/>

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Scala</strong>: My current role uses Scala as the primary language and have been building applications in Scala for the last two years. I am familiar with a range of Scala libraries, such as <a target="_blank" href="https://automateddeveloper.blogspot.com/2017/12/an-opinionated-guide-to-building-apis.html"> Akka-Http for building microservices</a> and <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/09/generic-programming-with-scala.html"> Shapeless for generic programming</a>, as well as familiar with a range of <a target="_blank" href="https://basementcrowd.com/2018/11/28/scala-the-aux-pattern-path-dependent-types/" >functional programming techniques available</a>.<br/><br/>
   <strong>Java</strong>: I am experienced in a variety of Java API’s and frameworks. I have worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others. <br/><br/>
   <strong>Groovy</strong> I have used Groovy as a language in production for ~4 years and I am familiar with many of the languages features (such as writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>) and quirks (such as <a target="_blank" href="https://dzone.com/articles/groovy-retrospective-an-addendum-memory-usage-perm">memory leak issues</a>). <br/><br/>
   <strong>Cloud platforms</strong>: I have primarily used AWS for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of AWS offerings, including EC2, RDS, S3, Cogito, <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/05/serverless-with-aws-lambda-scala.html">Lambda</a> and its more recent <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/10/machine-learning-with-aws-scala.html">Machine Learning capabilities</a>.<br/><br/>
   <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap, LESS, SASS, Backbone/Underscore/Require. More recently I have written React applications (primarily using the Create React App framework, and extending them)<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/AWS. <br/><br/>
   As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="https://projects.spring.io/spring-social/">https://projects.spring.io/spring-social/</a>. <br/><br/>
   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="https://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
